### PR TITLE
adding FLUENT 18.2  easyconfig

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@algiar yea use "@" and then reference the name of person. I got an email. The change you did looks fine and I think you use the Git interface which is the right way to do things. I think the change looks fine, we have to confirm if the license information will work. I suspect flex server might be different for Andover so that may be another complication.

**Comment by shahzebsiddiqui** [comment]
@algiar I think this change looks fine, I have rebuild FLUENT several times and I think this should be okay. If this is okay, please review and accept changes.

**Comment by shahzebsiddiqui** [comment]
@algiar  who is @saskialt

**Comment by algiar** [comment]
HI @shahzebsiddiqui ,
Sorry, it was me. I have the session opened with the user of our community manager, since we were configuring her github account yesterday. Since this repo is public, I did not notice I was not logged with my user. Sorry for creating confusion.

**Pull request merged**
